### ISSUE TITLE
Straightforward question

### ISSUE THREAD

**Issue by janban-outlook** [PapaSmurf/hello-world#1]
Hi there,

I was trying to use the name PapaSmurf on Github, but it appears already taken by you.
You do not seems to use it very actively. Are you willing to give it up, to make it available for me?

I am using papasmurf as my nickname, and also own the papasmurf.nl domain.

Do not feel obliged to, I am just asking....

Thanks
Jan van Veldhuizen, aka PapaSmurf

**Comment by PapaSmurf** [comment]
Hi! well, I have been using PapaSmurf for like 20 years in various forums. I recently got rejuivinated to start something new. thank you though. I love Blender!

**Comment by janban-outlook** [comment]
Ok then. I am having a namesake, at least :-)
